# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  shellcheck:
    name: Shellcheck
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Validate POSIX compatibility.
      - name: run shellcheck dash
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --shell=dash
        with:
          additional_files: 'bin/phinx-cake2.sh'

  # Composer config validation
  composer:
    name: Composer config validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate --strict

  # PHP syntax validation
  php:
    name: PHP syntax validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PHP syntax of config/phinx.php
        run: php -l config/phinx.php

  # phpstan for several php versions
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1, 8.2, 8.3] 
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: ${{ matrix.php_version }}
          configuration: phpstan.neon
          path: config/

